<a href="https://colab.research.google.com/github/ravina029/practicegit/blob/main/PythonPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def add(*n):
  sum=0
  for n1 in n:
    sum=sum+n1
  print(sum)

add(1,2,3,4,5)


15


In [ ]:
add(10)

10


In [ ]:
def info(**kwarg):
  for k,v in kwarg.items():
    print(k,"=",v)
info(roll_no=10, name="ravina", institute="Technion", address="Technion city, Haifa")


roll_no = 10
name = ravina
institute = Technion
address = Technion city, Haifa


In [ ]:
I=[1,2,34,4,5,8]
list(filter(lambda x:x%2==0,I))

[2, 34, 4, 8]

In [ ]:
list(map(lambda x: x*x,I))

[1, 4, 1156, 16, 25, 64]

In [ ]:
list(map(lambda x: x+x*x+1,I))

[3, 7, 1191, 21, 31, 73]

In [ ]:
from random import *

In [ ]:
for i in range(10):
  print(uniform(1,10))

2.6317160462604727
1.8314133078144046
5.573831670266876
6.389450805154769
1.8467346303267305
4.543776732316776
9.905856594210137
9.592670241514456
7.217137002252057
7.019898370504804


In [ ]:
print(uniform(1,10)) #gives random values between 0 to 1 not inclusive

4.562709906916348


In [ ]:
random.seed(19)
print(randint(1,10)) # gives random integer between 1 to 10

1


In [ ]:
print(random()) #produce random number between 0 and 1

0.4372328997179694


In [ ]:
randrange(10)

8

In [ ]:
for i in range(10):
   print(randrange(1,10,2))

3
9
5
3
1
7
3
5
3
9


In [ ]:
A=[2,3,4,5,54,566,78]
for i in range (1,10):
  print(choice(A))

54
3
54
4
2
4
5
4
4


In [ ]:
seed=10
print(choice(A))

566


In [ ]:
import random

# Set the seed to a specific value (e.g., 19)
random.seed(19)

# Generate and print a random number between 1 and 10
random_number = random.randint(1, 10)
print("Generated random number:", random_number)



Generated random number: 1


In [ ]:
class Ravina:
  print("let's learn about the class")
print(Ravina.__doc__)
help(Ravina)

let's learn about the class
None
Help on class Ravina in module __main__:

class Ravina(builtins.object)
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [ ]:
class Student:
  'Developed by durga for python demo'
  def __init__(self,*arg):
       self.name='durga'
       self.age=40
       self.marks=80
  def talk(self):
      print("Hello I am :",self.name)
      print("My Age is:",self.age)
      print("My Marks are:",self.marks)
a=Student("Ravina",29,97)
a.talk()

Hello I am : durga
My Age is: 40
My Marks are: 80


In [ ]:
#from typing_extensions import AsyncGenerator

class student:
  def __init__(self,*arg):
    print("we have initialize all the information about the sudent")
    self.name=arg[0]
    self.age=23
    self.roll=2
    self.marks=98
  def performance(self):
    print("performance of the student is quite well. and the name of the student is:", self.name)

s1=student("Ravina")
s2=student("Urvashi")
s3=student("Jayant")
s1.performance()
s2.performance()
s3.performance()



we have initialize all the information about the sudent
we have initialize all the information about the sudent
we have initialize all the information about the sudent
performance of the student is quite well. and the name of the student is: Ravina
performance of the student is quite well. and the name of the student is: Urvashi
performance of the student is quite well. and the name of the student is: Jayant


In [ ]:
class Student:
    def __init__(self, *args):
        #print("we have initialized all the information about the student")
        self.student_name = args[0]  # Use a different attribute name
        self.age = 23
        self.roll = 2
        self.marks = 98

    def performance(self):
        print("Performance of the student is quite well. The name of the student is:", self.student_name)

s1 = Student
s1.d=10
print(s1.__dict__)



{'__module__': '__main__', '__init__': <function Student.__init__ at 0x7f7180aa7c70>, 'performance': <function Student.performance at 0x7f7180aa75b0>, '__dict__': <attribute '__dict__' of 'Student' objects>, '__weakref__': <attribute '__weakref__' of 'Student' objects>, '__doc__': None, 'd': 10}


In [ ]:
print(Student.__dict__)

{'__module__': '__main__', '__init__': <function Student.__init__ at 0x7f7180aa72e0>, 'performance': <function Student.performance at 0x7f7180aa5fc0>, '__dict__': <attribute '__dict__' of 'Student' objects>, '__weakref__': <attribute '__weakref__' of 'Student' objects>, '__doc__': None}


In [ ]:
class Fruits:
  def __init__(self,*arg):
    self.f1="orange"
    self.f2="banana"
    self.f3="cheeku"
    self.f4="Peach"
  def test(self):
    print(f"{self.f1} taste sauer \n {self.f2} taste sweet \n {self.f3} taste super sweet \n {self.f4} taste sauer and sweet")


f=Fruits()
g=Fruits()
del f.f1

g.test()



orange taste sauer 
 banana taste sweet 
 cheeku taste super sweet 
 Peach taste sauer and sweet


# Handle the exceptions

In [ ]:
try:
  print(34/0)
except ZeroDivisionError as msg:
  print("there is an error, enter the valid number. And the error is:",msg)
finally:
  print("This statement is executed in the finally block.")



there is an error, enter the valid number. And the error is: division by zero
This statement is executed in the finally block.


# Nested try except and finally block

In [ ]:
try:
  print("This is the first outer try block")
  try:
      int(input("Enter a number:"))
  except ValueError as msg:
      print("Enter a valid number, inappropriate entry will raise the error:",msg)
  finally:
      print("Yay, we are done with the inside block")
except ZeroDivisionError as msg:
  print("there is an error, enter the valid number. And the error is:",msg)
finally:
  print("This statement is executed in the finally block.")

This is the first outer try block
Enter a number:ten
Enter a valid number, inappropriate entry will raise the error, invalid literal for int() with base 10: 'ten'
Yay, we are done with the inside block
This statement is executed in the finally block.


# Above are the predefined errors in the python, we can also raise our own custom errors.

In [ ]:
class TooyoungException(Exception):
  def __init__(self,arg):
    self.msg=arg

class TooyoungOld(Exception):
  def __init__(self,arg):
    self.msg=arg

age=int(input("Enter your age:"))
if age<18:
  raise TooyoungException("Please waite for some time And you will the corect match")

elif age>60:
  raise TooyoungOld("You are too old, probaly your marrige age has passed, best of you find a match")
else:
  print("You will get your match details soon on the mail id given by you.")




Enter your age:24
You will get your match details soon on the mail id given by you.


# Decorators: If we want to extend the functionality of a function without changing it then we use decorators.

In [ ]:
def greeting(func):
  def hey(name):
    if name=="ravina":
      return print(f"hello {name} good morning, you are doing well")
    else:
      return func(name)
  return hey
@greeting
def hello(name):
  print(f"hello {name } good morning, you are best in your work")


hello("ravina")
hello("jayant")
hello("papa")
hello("ritu")
hello("deepak")

hello ravina good morning, you are doing well
hello jayant good morning, you are best in your work
hello papa good morning, you are best in your work
hello ritu good morning, you are best in your work
hello deepak good morning, you are best in your work


# Calling function with decorator without without using a decorator

In [ ]:
def greeting(func):
  def hey(name):
    if name=="ravina":
      return print(f"hello {name} good morning, you are doing well")
    else:
      return func(name)
  return hey

def hello(name):
  print(f"hello {name } good morning, you are best in your work")


greeting(hello("ravina"))
greeting(hello("jayant"))
greeting(hello("papa"))
greeting(hello("ritu"))
greeting(hello("deepak"))

hello ravina good morning, you are best in your work
hello jayant good morning, you are best in your work
hello papa good morning, you are best in your work
hello ritu good morning, you are best in your work
hello deepak good morning, you are best in your work


<function __main__.greeting.<locals>.hey(name)>

In [ ]:
def carefull_devision(division):
  def devide(a,b):
    if b==0:
      print("ooops, devision can't be performed")
      return
    else:
      return division(a,b)
  return devide


@carefull_devision
def division(a,b):
  return print("result of the devision is :", a/b)

division(2,3)
division(10,2)
#division(2,0)

result of the devision is : 0.6666666666666666
result of the devision is : 5.0


In [ ]:
def add(func):
  def operation(a,b):
    return a+b
  return operation

def mul(func):
  def operation(a,b):
    return a*b
  return operation

@add
@mul
def number(a,b):
  return a,b



number(2,3)
number(5,6)

11

Generator functions: which are resposible for generating a sequence of values usiang the yield method. and the outputs can be recieved using the next word.


In [ ]:
def my_gen():
  yield "A"
  yield "B"
  yield "C"

gen=my_gen()
print(type(gen))

print(next(gen))
print(next(gen))
print(next(gen))
#print(next(gen))  #it will raise Stopiteration error. because the fucntion goes out of value.


<class 'generator'>
A
B
C


In [ ]:
def iteration(n):
  print("Start the contious iteration. this is to demostarate a different usecase of geneartor function")

  while(n>0):
    yield n
    n=n-1
iter=iteration(5)
for i in (iter):
   print(i)

Start the contious iteration. this is to demostarate a different usecase of geneartor function
5
4
3
2
1


In [ ]:
I=[x*x for x in range(10000000000000000)] #it will give memory error
print(I[0])

In [ ]:
# with the help of generators we will not get any error but we will get only one value
g=(x*x for x in range(10000000000000000))
print(next(g))

0


# Assertion Statements

In [ ]:
def cubeit(x):
  return x**3

"""Following assert statenment will give the assertion error if there is any"""
assert cubeit(2)==8    #"Cube of tye given. number must be 8"
assert cubeit(3)==27   # Cube of three should be 27

print(cubeit(2))
print(cubeit(3))

8
27


In [ ]:
def verification(name):    #following programmme will give the same statement over and over again.
  return "king"
assert verification("queen") #"""the appeared person is not vthe same"""

verification("queen")

'king'

# handeling binery or text files in python

In [ ]:
f=open("file.text","w")       #you can check for r,a,r+,w+,a+, and for exclusive creation mode.
print("file name is",f.name)
print("file is readable",f.mode)
print("file is closed",f.closed)
f.close()
print("file is closed", f.closed)

file name is file.text
file is readable w
file is closed False
file is closed True


# folowing code snippet will give some strange result.

In [ ]:
f=open("file.text","w")
f.write("i need to add some important information\n")
f.write("this is python. practice modeule's part\n")
f.write("Every concept will be overed thoroughly")
#print("data written to the file succesfully")
#f.close()


39

In [ ]:
f=open("a.txt","w")
l=["ramji\n","shyam\n",'ritu\n','nachhi\n','jayant\n',"ravina"]
f.writelines(l)
print("list of the line written to the file succesfully")
f.close()

list of the line written to the file succesfully


In [ ]:
f=open("a.txt","r")
data=f.read()
print(data)
f.close()

ramji
shyam
ritu
nachhi
jayant
ravina


In [ ]:
#To read only first ten characters
f=open("a.txt","r")
data=f.read(10)
print(data)
f.close()

ramji
shya


In [ ]:
# To read lines in the form of list
f=open("a.txt","r")
data=f.read()
l=[print(x,end="") for x in data]
l
f.close()

ramji
shyam
ritu
nachhi
jayant
ravina

# With statement:
The advantage of with statement is it will take care closing of file,after completing all operations automatically even in the case of exceptions also, and we are not required to close explicitly.

In [ ]:
with open("a.txt","w") as f:
  data=f.write("hello world")
  print(data)
  print("the file is closed", f.closed)

print("the file is closed", f.closed)

11
the file is closed False
the file is closed True


In [ ]:
line="a quick fox jump over the lazy little dog"
for word in line:
  print(word,"\t",end="")

a 	  	q 	u 	i 	c 	k 	  	f 	o 	x 	  	j 	u 	m 	p 	  	o 	v 	e 	r 	  	t 	h 	e 	  	l 	a 	z 	y 	  	l 	i 	t 	t 	l 	e 	  	d 	o 	g 	

In [ ]:
line="a quick fox jump over the lazy little dog"
for word in line:
  print(word,"\t")

a 	
  	
q 	
u 	
i 	
c 	
k 	
  	
f 	
o 	
x 	
  	
j 	
u 	
m 	
p 	
  	
o 	
v 	
e 	
r 	
  	
t 	
h 	
e 	
  	
l 	
a 	
z 	
y 	
  	
l 	
i 	
t 	
t 	
l 	
e 	
  	
d 	
o 	
g 	


In [ ]:
# To know the current working directory
import os
cwd=os.getcwd()
print("the current working directory is :",cwd)

the current working directory is : /content


In [ ]:
import os
print(os.listdir("."))

['.config', 'sample_data']


In [ ]:
"""Note:To display contents of particular directory, we have to provide that directory name as argument to walk() function.
os.walk("directoryname")
Q) Whati st h edifferencebetweenlistdir)a n dwalk()Functions?
In the case of listdir), we will get contents of specified directory but not sub directory contents. But in the case of walk() function we will get contents of specifled directory and its sub directories also."""
os.walk("/content")

<generator object _walk at 0x7e48be74dd20>

In [ ]:
import stat

In [ ]:
"""We canget statistics of afile like size, last accessed time,last modified time etc by using stat() function of os module."""
f=open("a.txt","r")
stats=os.stat('a.txt') #first open the file the apply this operation
print(stats)


os.stat_result(st_mode=33188, st_ino=2621507, st_dev=52, st_nlink=1, st_uid=0, st_gid=0, st_size=37, st_atime=1693108323, st_mtime=1693108321, st_ctime=1693108321)


# Pickling and Unpickling of Obiects:
 the process of writing state of object to the file is called pickling and the process of reading state of an object from the file is called unpicking.

# Inheritence of one class into the other

In [ ]:
class C1:
  def f1(self):
    print("this is a parent class and we will execute this just to see wether we are able to learn the concept of inheritance")

class C2(C1):
  def f2(self):
    print("this is a child class")

class C3(C2):
  def f3(self):
    print("this is subchild method")

c=C3()
c.f1()
c.f2()
c.f3()

this is a parent class and we will execute this just to see wether we are able to learn the concept of inheritance
this is a child class
this is subchild method


# Hierarchical inheritance:
The concept of inheriting properties from one class into multiple classes which are present at same level is known as Hierarchical Inheritance

In [ ]:
class C1:
  def f1(self):
    print("this is a parent class and we will execute this just to see wether we are able to learn the concept of inheritance")

class C2(C1):
  def f2(self):
    print("this is a child class1")

class C3(C1):
  def f3(self):
    print("this is child class2")

c=C2()
c1=C3()
c.f1()
c.f2()
c1.f3()



this is a parent class and we will execute this just to see wether we are able to learn the concept of inheritance
this is a child class1
this is child class2


# Multiple Inheritance:
The concept of inheriting the properties from multiple classes into a single class at a
time, is known as multiple inheritance.

In [ ]:
class C2():
  def f2(self):
    print("this is child1")

class C3():
  def f3(self):
    print("this is child2")
class C1(C2,C3):
  def f1(self):
    print("this is a parent class and we will execute this just to see wether we are able to learn the concept of inheritance")

C=C1()
C.f1()
C.f2()
C.f3()


this is a parent class and we will execute this just to see wether we are able to learn the concept of inheritance
this is child1
this is child2


In [ ]:
l=[1,23,34,4,5,6,7]
sum(l)

80

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample categorical data
categorical_data = ['red', 'green', 'blue', 'red', 'green']

# Reshape data to a 2D array
categorical_data = np.array(categorical_data).reshape(-1, 1)

# Create an instance of OneHotEncoder
encoder = OneHotEncoder()

# Fit the encoder on your categorical data and transform it
encoded_data = encoder.fit_transform(categorical_data)

# Convert the encoded sparse matrix to an array
encoded_array = encoded_data.toarray()

print("Original data:")
print(categorical_data)
print("\nEncoded data:")
print(encoded_array)


Original data:
[['red']
 ['green']
 ['blue']
 ['red']
 ['green']]

Encoded data:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [ ]:
A=[[0,7,3],
   [3,4,6],
   [1,10,7]]
import numpy as np

In [ ]:
temp2=np.sort(A)
temp2

array([[ 0,  3,  7],
       [ 3,  4,  6],
       [ 1,  7, 10]])

In [ ]:
A = np.array([[2, 9, 7], [1, 5, 8], [6, 0, 9]])
A

array([[2, 9, 7],
       [1, 5, 8],
       [6, 0, 9]])

In [ ]:
#A.sort()

In [ ]:
A

array([[2, 7, 9],
       [1, 5, 8],
       [0, 6, 9]])

In [ ]:
np.sort(A)

array([[2, 7, 9],
       [1, 5, 8],
       [0, 6, 9]])

In [2]:
import numpy as np
X=np.random.randn(10,4)
X

array([[-1.56531224, -0.67252618, -1.05743393, -0.22833343],
       [ 1.39338923, -0.26405753,  0.0237197 ,  2.28146774],
       [-0.86646098,  0.30311493,  2.87703205,  1.00302062],
       [-1.00612357, -1.33269777, -1.18356911, -0.28366989],
       [-0.24521633, -0.1884743 ,  0.78730895,  0.51656405],
       [-0.25228063,  1.01917231, -0.03074493,  1.89853673],
       [ 1.12772783,  0.46315239, -1.93744257,  0.19224343],
       [ 2.16629369, -0.58365803,  0.62065183,  0.18782978],
       [ 0.50093962, -0.17504445,  0.26113415,  1.59958457],
       [ 2.02801286, -0.25544198, -0.02274943, -1.078434  ]])